from typing import Callable, Any

_CallbackType = Callable[[], Any]

class Callback:
    # __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self): ...

class WeakMethod:
    # __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, meth: _CallbackType) -> None: ...
    def __reduce__(self): ...
