from types import MethodType


class Callback:
    # __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self): ...

class WeakMethod:
    # __pyx_vtable__: ClassVar[PyCapsule] = ...
    def __init__(self, meth: MethodType) -> None: ...
    def __reduce__(self): ...
